# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-29 08:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('activityid', models.AutoField(primary_key=True, serialize=False)),
                ('duration', models.IntegerField()),
                ('datetime', models.DateTimeField()),
                ('activityname', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('entryid', models.AutoField(primary_key=True, serialize=False)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leadsMasterApp.Activity')),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('idcompany', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Generalbusinessplans',
            fields=[
                ('planid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('commission', models.FloatField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leadsMasterApp.Company')),
            ],
        ),
        migrations.CreateModel(
            name='GeneralContract',
            fields=[
                ('idcontract', models.IntegerField(primary_key=True, serialize=False)),
                ('issuedate', models.DateTimeField()),
                ('expirationdate', models.DateTimeField()),
                ('annualpremium', models.FloatField()),
                ('doses', models.IntegerField(blank=True, null=True)),
                ('nextpayment', models.DateTimeField(blank=True, null=True)),
                ('price', models.FloatField()),
                ('notes', models.CharField(max_length=80)),
                ('active', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Lifebusinessplans',
            fields=[
                ('planlifeid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('firstyearcommission', models.FloatField()),
                ('maxpercentage', models.IntegerField(blank=True, null=True)),
                ('minpercentage', models.IntegerField(blank=True, null=True)),
                ('futureprofit', models.FloatField()),
                ('futureprofit2', models.FloatField(blank=True, null=True)),
                ('futureprofit3', models.FloatField(blank=True, null=True)),
                ('futureprofit4', models.FloatField(blank=True, null=True)),
                ('agelimit', models.IntegerField()),
                ('duration', models.IntegerField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leadsMasterApp.Company')),
            ],
        ),
        migrations.CreateModel(
            name='LifeContract',
            fields=[
                ('idcontract', models.IntegerField(primary_key=True, serialize=False)),
                ('issuedate', models.DateTimeField(verbose_name='date issued')),
                ('expirationdate', models.DateTimeField(verbose_name='expiration date')),
                ('annualpremium', models.FloatField()),
                ('doses', models.IntegerField(blank=True, null=True)),
                ('nextpayment', models.DateTimeField(blank=True, null=True)),
                ('price', models.FloatField()),
                ('notes', models.CharField(max_length=80)),
                ('active', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('idperson', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('surname', models.CharField(max_length=30)),
                ('telephone', models.CharField(max_length=15)),
                ('email', models.CharField(blank=True, max_length=45, null=True)),
                ('dateofbirth', models.DateField()),
                ('isintroducer', models.IntegerField(choices=[(1, 'Yes'), (0, 'No')], default=0)),
                ('isclient', models.IntegerField(choices=[(1, 'Yes'), (0, 'No')], default=0)),
                ('wasclient', models.IntegerField(choices=[(1, 'Yes'), (0, 'No')], default=0)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employeeid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='leadsMasterApp.Person')),
                ('position', models.CharField(max_length=45)),
                ('salary', models.FloatField()),
                ('hourspermonth', models.IntegerField()),
                ('password', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('website', models.URLField(blank=True)),
                ('employeeid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='leadsMasterApp.Person')),
                ('position', models.CharField(max_length=45)),
                ('salary', models.FloatField()),
                ('hourspermonth', models.IntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='person',
            name='leadfrom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='leadsMasterApp.Person'),
        ),
        migrations.AddField(
            model_name='lifecontract',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leadsMasterApp.Person'),
        ),
        migrations.AddField(
            model_name='lifecontract',
            name='plan',
            field=models.ManyToManyField(to='leadsMasterApp.Lifebusinessplans'),
        ),
        migrations.AddField(
            model_name='generalcontract',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leadsMasterApp.Person'),
        ),
        migrations.AddField(
            model_name='generalcontract',
            name='plan',
            field=models.ManyToManyField(to='leadsMasterApp.Generalbusinessplans'),
        ),
        migrations.AddField(
            model_name='activity',
            name='customerid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='leadsMasterApp.Person'),
        ),
        migrations.AddField(
            model_name='calendar',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leadsMasterApp.Employee'),
        ),
    ]
