# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-29 09:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leadsMasterApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalcontract',
            name='id',
            field=models.AutoField(default=0, primary_key=True, serialize=False, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lifecontract',
            name='id',
            field=models.AutoField(default=0, primary_key=True, serialize=False, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='id',
            field=models.AutoField(default=0, primary_key=True, serialize=False, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='generalcontract',
            name='idcontract',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='lifecontract',
            name='idcontract',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='idperson',
            field=models.IntegerField(unique=True),
        ),
    ]
