# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-15 12:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leadsMasterApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalbusinessplans',
            name='commission',
            field=models.FloatField(),
        ),
        migrations.RemoveField(
            model_name='person',
            name='generalcontracts',
        ),
        migrations.AddField(
            model_name='person',
            name='generalcontracts',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='leadsMasterApp.GeneralContract'),
        ),
        migrations.RemoveField(
            model_name='person',
            name='lifecontracts',
        ),
        migrations.AddField(
            model_name='person',
            name='lifecontracts',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='leadsMasterApp.LifeContract'),
        ),
    ]
