# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-29 10:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leadsMasterApp', '0002_auto_20161229_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalcontract',
            name='idcontract',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='lifecontract',
            name='idcontract',
            field=models.IntegerField(),
        ),
    ]
