# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-15 12:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leadsMasterApp', '0002_auto_20161115_1207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='generalcontracts',
        ),
        migrations.RemoveField(
            model_name='person',
            name='lifecontracts',
        ),
        migrations.AddField(
            model_name='generalcontract',
            name='client',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='leadsMasterApp.Person'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lifecontract',
            name='client',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='leadsMasterApp.Person'),
            preserve_default=False,
        ),
    ]
