# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-17 18:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leadsMasterApp', '0003_auto_20161115_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalcontract',
            name='price',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lifecontract',
            name='price',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
