# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-25 20:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leadsMasterApp', '0004_auto_20161117_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='isclient',
            field=models.IntegerField(choices=[(1, 'Yes'), (0, 'No')]),
        ),
    ]
