# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-25 21:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leadsMasterApp', '0006_auto_20161125_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='isclient',
            field=models.IntegerField(choices=[(1, 'Yes'), (0, 'No')], default=0),
        ),
        migrations.AlterField(
            model_name='person',
            name='isintroducer',
            field=models.IntegerField(choices=[(1, 'Yes'), (0, 'No')], default=0),
        ),
    ]
