# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-29 13:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leadsMasterApp', '0006_auto_20161229_1325'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lifecontract',
            old_name='active',
            new_name='cancelled',
        ),
        migrations.RemoveField(
            model_name='generalcontract',
            name='active',
        ),
        migrations.AddField(
            model_name='generalcontract',
            name='cancelled',
            field=models.BooleanField(default=False),
        ),
    ]
