# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-04 12:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leadsMasterApp', '0007_auto_20161125_2127'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lifebusinessplans',
            old_name='futureprofit1',
            new_name='futureprofit',
        ),
    ]
