# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-03 12:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leadsMasterApp', '0008_auto_20170102_1438'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='datetime',
            new_name='activityDate',
        ),
    ]
