# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-03 13:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leadsMasterApp', '0009_auto_20170103_1552'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='activityDate',
        ),
        migrations.AddField(
            model_name='activity',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 1, 3, 16, 24, 46, 47000)),
        ),
        migrations.AddField(
            model_name='activity',
            name='time',
            field=models.TimeField(default=datetime.datetime(2017, 1, 3, 16, 24, 46, 47000)),
        ),
    ]
