# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-07 07:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('leadsMasterApp', '0010_auto_20170103_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='activity',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
