# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-07 11:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leadsMasterApp', '0011_auto_20161207_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='wasclient',
            field=models.IntegerField(choices=[(1, 'Yes'), (0, 'No')], default=0),
        ),
    ]
