# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-07 18:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leadsMasterApp', '0011_auto_20170107_1041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lifebusinessplans',
            name='duration',
        ),
        migrations.AddField(
            model_name='lifecontract',
            name='duration',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
