# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-16 08:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leadsMasterApp', '0013_auto_20161216_0831'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['name']},
        ),
    ]
