# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-12 20:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leadsMasterApp', '0015_auto_20170111_2226'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=6),
        ),
        migrations.AddField(
            model_name='person',
            name='occupation',
            field=models.CharField(choices=[('Student', 'Student'), ('Banker', 'Banker'), ('Education Staff ', 'Education Staff'), ('Lawyer', 'Lawyer'), ('Enterpreneur', 'Enterpreneur'), ('Customer Service Employee', 'Customer Service Employee'), ('Public Sector ', 'Public Sector'), ('Private Sector ', 'Private Sector'), ('Other', 'Other')], default='None', max_length=60),
        ),
    ]
