# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-19 15:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('leadsMasterApp', '0018_auto_20170116_2145'),
    ]

    operations = [
        migrations.CreateModel(
            name='birthdayNot',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('email', models.BooleanField()),
                ('birthday', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leadsMasterApp.Person')),
            ],
        ),
        migrations.CreateModel(
            name='genPaymentsNot',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('email', models.BooleanField()),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leadsMasterApp.GeneralContract')),
            ],
        ),
        migrations.CreateModel(
            name='genRenewalsNot',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('email', models.BooleanField()),
                ('renewal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leadsMasterApp.GeneralContract')),
            ],
        ),
        migrations.CreateModel(
            name='lifePaymentsNot',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('email', models.BooleanField()),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leadsMasterApp.LifeContract')),
            ],
        ),
        migrations.CreateModel(
            name='lifeRenewalsNot',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('email', models.BooleanField()),
                ('renewal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leadsMasterApp.LifeContract')),
            ],
        ),
        migrations.AddField(
            model_name='activity',
            name='email',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
