# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-19 15:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leadsMasterApp', '0019_auto_20170119_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='email',
            field=models.BooleanField(default=False),
        ),
    ]
