# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-10 17:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leadsMasterApp', '0022_activity_meeting_minutes'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalbusinessplans',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lifebusinessplans',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
