# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-18 13:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leadsMasterApp', '0023_auto_20170310_1711'),
    ]

    operations = [
        migrations.RenameField(
            model_name='generalcontract',
            old_name='price',
            new_name='basicvalue',
        ),
        migrations.RenameField(
            model_name='lifecontract',
            old_name='price',
            new_name='basicvalue',
        ),
    ]
